import { useMemo, useState } from 'react';
import {
  BarChart3, CalendarCheck, CheckCircle2, Database, Download, DollarSign, Edit3, FileText, Plus, Search, Save, ShieldCheck, Trash2, TrendingUp, UserCheck, Users, Wallet, X,
} from 'lucide-react';

const money = (value) => `RM ${Number(value || 0).toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);
const newId = () => (typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `crm-${Date.now()}`);
const total = (rows, type) => rows.filter((row) => row.status !== 'Void' && (!type || row.type === type)).reduce((sum, row) => sum + Number(row.amount || 0), 0);

function statusTone(status) {
  const key = String(status || '').toLowerCase().replace(/\s/g, '-');
  if (['posted', 'approved', 'active', 'present', 'confirmed'].includes(key)) return 'positive';
  if (['pending', 'late', 'on-leave', 'new'].includes(key)) return 'attention';
  if (['void', 'rejected', 'inactive', 'absent'].includes(key)) return 'muted';
  return 'neutral';
}

function StatusBadge({ status }) { return <span className={`admin-status ${statusTone(status)}`}><i />{status}</span>; }
function branchesFor(state) { return ['All branches', ...(state.branches || []).map((branch) => branch.name)]; }
function exportRows(rows, filename, notify) { const header = Object.keys(rows[0] || {}).join(','); const body = rows.map((row) => Object.values(row).map((value) => JSON.stringify(Array.isArray(value) ? value.join('|') : value ?? '')).join(',')).join('\n'); const blob = new Blob([`${header}\n${body}`], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); notify('CSV export prepared.'); }

function Kpi({ icon: Icon, tone, label, value, meta }) { return <article className="admin-crm-kpi"><span className={`admin-crm-kpi-icon ${tone}`}><Icon size={18} /></span><span>{label}</span><strong className={tone === 'profit' ? 'is-positive' : ''}>{value}</strong><small>{meta}</small></article>; }

export function FinancePage({ state, commit, notify }) {
  const rows = state.financeTransactions || [];
  const [query, setQuery] = useState('');
  const [type, setType] = useState('All types');
  const [branch, setBranch] = useState('All branches');
  const [drawer, setDrawer] = useState(null);
  const branches = branchesFor(state);
  const filtered = useMemo(() => rows.filter((row) => `${row.description} ${row.category} ${row.reference || ''} ${row.branch}`.toLowerCase().includes(query.toLowerCase()) && (type === 'All types' || row.type === type) && (branch === 'All branches' || row.branch === branch)), [rows, query, type, branch]);
  const income = total(filtered, 'Income');
  const expenses = total(filtered, 'Expense');
  const net = income - expenses;
  const branchSummary = branches.filter((item) => item !== 'All branches').map((item) => ({ branch: item, income: total(rows.filter((row) => row.branch === item), 'Income'), expense: total(rows.filter((row) => row.branch === item), 'Expense') }));
  const maxBranchValue = Math.max(1, ...branchSummary.flatMap((item) => [item.income, item.expense]));
  const save = (draft) => { const clean = { ...draft, isNew: false, amount: Number(draft.amount || 0) }; commit((current) => ({ ...current, financeTransactions: current.financeTransactions.some((row) => row.id === clean.id) ? current.financeTransactions.map((row) => row.id === clean.id ? clean : row) : [clean, ...current.financeTransactions] })); setDrawer(null); notify('Finance transaction saved.'); };
  const voidRow = (id) => { commit((current) => ({ ...current, financeTransactions: current.financeTransactions.map((row) => row.id === id ? { ...row, status: 'Void' } : row) })); notify('Transaction marked as void.'); };
  return <section className="admin-crm-page">
    <div className="admin-crm-notice"><Database size={15} /><span><strong>Finance workspace</strong> Sample records are editable. Connect your POS, bank feed, or accounting export before using these figures for reporting.</span></div>
    <div className="admin-crm-kpi-grid"><Kpi icon={TrendingUp} tone="income" label="Income in view" value={money(income)} meta={`${filtered.filter((row) => row.type === 'Income').length} income records`} /><Kpi icon={TrendingUp} tone="expense" label="Expenses in view" value={money(expenses)} meta={`${filtered.filter((row) => row.type === 'Expense').length} expense records`} /><Kpi icon={BarChart3} tone="profit" label="Net operating result" value={money(net)} meta={income ? `${Math.round((net / income) * 100)}% operating margin` : 'No income recorded'} /><Kpi icon={Wallet} tone="cash" label="Transactions" value={filtered.length} meta={`Across ${new Set(filtered.map((row) => row.branch)).size || 0} branches`} /></div>
    <div className="admin-crm-grid">
      <section className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-panel-kicker">Branch cash flow</span><h2>Income vs expenses</h2></div><span className="admin-crm-legend"><i className="income" />Income <i className="expense" />Expenses</span></div><div className="admin-crm-branch-chart">{branchSummary.map((item) => <div className="admin-crm-branch-chart-row" key={item.branch}><div><strong>{item.branch}</strong><span>{money(item.income - item.expense)} net</span></div><div className="admin-crm-bar-track"><i className="income" style={{ width: `${(item.income / maxBranchValue) * 100}%` }} /><i className="expense" style={{ width: `${(item.expense / maxBranchValue) * 100}%` }} /></div></div>)}</div></section>
      <section className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-panel-kicker">Finance controls</span><h2>Keep records clean</h2></div><DollarSign size={18} /></div><div className="admin-crm-checklist"><span><CheckCircle2 size={15} />Post income after reconciliation</span><span><CheckCircle2 size={15} />Attach receipts to expenses</span><span><CheckCircle2 size={15} />Review branch cash weekly</span><span><ShieldCheck size={15} />Limit finance access to trusted roles</span></div><div className="admin-crm-action-row"><button className="admin-outline-button" onClick={() => exportRows(filtered, 'naseeb-finance.csv', notify)}><Download size={15} />Export CSV</button><button className="admin-primary-button" onClick={() => setDrawer(makeCrmRecord('finance'))}><Plus size={15} />Add transaction</button></div></section>
    </div>
    <div className="admin-toolbar admin-crm-toolbar"><label className="admin-search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search description, category, or reference..." /></label><select value={type} onChange={(event) => setType(event.target.value)} aria-label="Filter finance type"><option>All types</option><option>Income</option><option>Expense</option></select><select value={branch} onChange={(event) => setBranch(event.target.value)} aria-label="Filter finance branch">{branches.map((item) => <option key={item}>{item}</option>)}</select></div>
    <div className="admin-table-panel"><div className="admin-table-top"><span>{filtered.length} finance records</span><span>Posted values are included in reporting</span></div><div className="admin-table-wrap"><table className="admin-table admin-crm-table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Branch</th><th>Method</th><th>Amount</th><th>Status</th><th aria-label="Actions" /></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td>{row.transactionDate}</td><td><strong>{row.description}</strong><small className="admin-cell-note">{row.reference || 'No reference'}</small></td><td>{row.category}</td><td>{row.branch}</td><td>{row.paymentMethod}</td><td className={row.type === 'Income' ? 'admin-crm-income' : 'admin-crm-expense'}>{row.type === 'Income' ? '+' : '-'}{money(row.amount)}</td><td><StatusBadge status={row.status} /></td><td><div className="admin-row-actions"><button className="admin-icon-button small" aria-label={`Edit ${row.description}`} onClick={() => setDrawer(row)}><Edit3 size={14} /></button><button className="admin-icon-button small" aria-label={`Void ${row.description}`} onClick={() => voidRow(row.id)}><Trash2 size={14} /></button></div></td></tr>)}</tbody></table>{!filtered.length && <div className="admin-empty-panel"><Search size={24} /><h3>No finance records found</h3><p>Change the filters or add the first income or expense.</p></div>}</div></div>
    {drawer && <CrmDrawer kind="finance" record={drawer} state={state} onSave={save} onClose={() => setDrawer(null)} />}
  </section>;
}

export function HrPage({ state, commit, notify }) {
  const staff = state.staff || [];
  const attendance = state.attendance || [];
  const leaveRequests = state.leaveRequests || [];
  const [tab, setTab] = useState('staff');
  const [query, setQuery] = useState('');
  const [branch, setBranch] = useState('All branches');
  const [drawer, setDrawer] = useState(null);
  const branches = branchesFor(state);
  const activeStaff = staff.filter((row) => row.status === 'Active');
  const filteredStaff = useMemo(() => staff.filter((row) => `${row.fullName} ${row.employeeCode} ${row.role} ${row.email}`.toLowerCase().includes(query.toLowerCase()) && (branch === 'All branches' || row.branch === branch)), [staff, query, branch]);
  const filteredAttendance = useMemo(() => attendance.filter((row) => `${row.staffName} ${row.status} ${row.branch}`.toLowerCase().includes(query.toLowerCase()) && (branch === 'All branches' || row.branch === branch)), [attendance, query, branch]);
  const filteredLeave = useMemo(() => leaveRequests.filter((row) => `${row.staffName} ${row.leaveType} ${row.status}`.toLowerCase().includes(query.toLowerCase()) && (branch === 'All branches' || row.branch === branch)), [leaveRequests, query, branch]);
  const save = (kind, draft) => { const key = kind === 'staff' ? 'staff' : kind === 'attendance' ? 'attendance' : 'leaveRequests'; const clean = { ...draft, isNew: false, salary: kind === 'staff' ? Number(draft.salary || 0) : draft.salary }; commit((current) => ({ ...current, [key]: current[key].some((row) => row.id === clean.id) ? current[key].map((row) => row.id === clean.id ? clean : row) : [clean, ...current[key]] })); setDrawer(null); notify(`${kind === 'staff' ? 'Staff member' : kind === 'attendance' ? 'Attendance record' : 'Leave request'} saved.`); };
  const updateLeave = (id, status) => { commit((current) => ({ ...current, leaveRequests: current.leaveRequests.map((row) => row.id === id ? { ...row, status } : row) })); notify(`Leave request ${status.toLowerCase()}.`); };
  const payroll = activeStaff.reduce((sum, row) => sum + Number(row.salary || 0), 0);
  return <section className="admin-crm-page">
    <div className="admin-crm-notice"><Users size={15} /><span><strong>HR workspace</strong> Staff and payroll records are private operational data. Confirm roles, salaries, and local employment requirements before production use.</span></div>
    <div className="admin-crm-kpi-grid"><Kpi icon={Users} tone="cash" label="Total staff" value={staff.length} meta={`${activeStaff.length} active employees`} /><Kpi icon={UserCheck} tone="profit" label="Attendance today" value={attendance.filter((row) => row.attendanceDate === today() && row.status === 'Present').length} meta="Present records" /><Kpi icon={CalendarCheck} tone="expense" label="Leave awaiting review" value={leaveRequests.filter((row) => row.status === 'Pending').length} meta="Requests in queue" /><Kpi icon={Wallet} tone="income" label="Monthly payroll plan" value={money(payroll)} meta="Active staff salary total" /></div>
    <div className="admin-panel admin-hr-panel"><div className="admin-hr-tabs" role="tablist" aria-label="HR sections"><button className={tab === 'staff' ? 'active' : ''} onClick={() => setTab('staff')} role="tab" aria-selected={tab === 'staff'}><Users size={15} />Staff directory</button><button className={tab === 'attendance' ? 'active' : ''} onClick={() => setTab('attendance')} role="tab" aria-selected={tab === 'attendance'}><CalendarCheck size={15} />Attendance</button><button className={tab === 'leave' ? 'active' : ''} onClick={() => setTab('leave')} role="tab" aria-selected={tab === 'leave'}><FileText size={15} />Leave requests</button></div><div className="admin-toolbar admin-crm-toolbar"><label className="admin-search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={tab === 'staff' ? 'Search staff, role, or employee ID...' : 'Search HR records...'} /></label><select value={branch} onChange={(event) => setBranch(event.target.value)} aria-label="Filter HR branch">{branches.map((item) => <option key={item}>{item}</option>)}</select><button className="admin-outline-button" onClick={() => exportRows(tab === 'staff' ? filteredStaff : tab === 'attendance' ? filteredAttendance : filteredLeave, `naseeb-${tab}.csv`, notify)}><Download size={15} />Export</button>{tab !== 'leave' && <button className="admin-primary-button" onClick={() => setDrawer({ kind: tab, record: makeCrmRecord(tab, state) })}><Plus size={15} />{tab === 'staff' ? 'Add staff' : 'Mark attendance'}</button>}</div>{tab === 'staff' && <StaffTable rows={filteredStaff} onEdit={(record) => setDrawer({ kind: 'staff', record })} />}{tab === 'attendance' && <AttendanceTable rows={filteredAttendance} />}{tab === 'leave' && <LeaveTable rows={filteredLeave} onUpdate={updateLeave} />}</div>
    {drawer && <CrmDrawer kind={drawer.kind} record={drawer.record} state={state} onSave={(draft) => save(drawer.kind, draft)} onClose={() => setDrawer(null)} />}
  </section>;
}

function StaffTable({ rows, onEdit }) { return <div className="admin-table-panel"><div className="admin-table-top"><span>{rows.length} staff records</span><span>Salary totals are planning values</span></div><div className="admin-table-wrap"><table className="admin-table admin-crm-table"><thead><tr><th>Employee</th><th>Role</th><th>Branch</th><th>Employment</th><th>Salary</th><th>Status</th><th aria-label="Actions" /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="admin-table-primary"><span className="admin-avatar small">{row.fullName?.slice(0, 2).toUpperCase()}</span><span><strong>{row.fullName}</strong><small>{row.employeeCode} · {row.phone}</small></span></div></td><td>{row.role}</td><td>{row.branch}</td><td>{row.employmentType}</td><td>{money(row.salary)}</td><td><StatusBadge status={row.status} /></td><td><button className="admin-icon-button small" aria-label={`Edit ${row.fullName}`} onClick={() => onEdit(row)}><Edit3 size={14} /></button></td></tr>)}</tbody></table>{!rows.length && <div className="admin-empty-panel"><Users size={24} /><h3>No staff records found</h3><p>Add a staff member or clear the filters.</p></div>}</div></div>; }
function AttendanceTable({ rows }) { return <div className="admin-table-panel"><div className="admin-table-top"><span>{rows.length} attendance records</span><span>Track daily status and working hours</span></div><div className="admin-table-wrap"><table className="admin-table admin-crm-table"><thead><tr><th>Date</th><th>Employee</th><th>Branch</th><th>Clock in</th><th>Clock out</th><th>Status</th><th>Notes</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.attendanceDate}</td><td><strong>{row.staffName}</strong><small className="admin-cell-note">{row.employeeCode}</small></td><td>{row.branch}</td><td>{row.clockIn || '—'}</td><td>{row.clockOut || '—'}</td><td><StatusBadge status={row.status} /></td><td>{row.notes || '—'}</td></tr>)}</tbody></table>{!rows.length && <div className="admin-empty-panel"><CalendarCheck size={24} /><h3>No attendance records found</h3><p>Mark attendance for the team from the action above.</p></div>}</div></div>; }
function LeaveTable({ rows, onUpdate }) { return <div className="admin-table-panel"><div className="admin-table-top"><span>{rows.length} leave requests</span><span>Approve requests only after manager review</span></div><div className="admin-table-wrap"><table className="admin-table admin-crm-table"><thead><tr><th>Employee</th><th>Leave type</th><th>Dates</th><th>Branch</th><th>Reason</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.staffName}</strong><small className="admin-cell-note">{row.employeeCode}</small></td><td>{row.leaveType}</td><td>{row.startDate} – {row.endDate}</td><td>{row.branch}</td><td>{row.reason || '—'}</td><td><StatusBadge status={row.status} /></td><td>{row.status === 'Pending' ? <div className="admin-row-actions"><button className="admin-outline-button admin-mini-button" onClick={() => onUpdate(row.id, 'Approved')}>Approve</button><button className="admin-link-button" onClick={() => onUpdate(row.id, 'Rejected')}>Reject</button></div> : '—'}</td></tr>)}</tbody></table>{!rows.length && <div className="admin-empty-panel"><FileText size={24} /><h3>No leave requests found</h3><p>New staff leave requests will appear here.</p></div>}</div></div>; }

function makeCrmRecord(kind, state = {}) {
  const branch = branchesFor(state).find((item) => item !== 'All branches') || '';
  if (kind === 'finance') return { id: newId(), isNew: true, type: 'Expense', description: '', category: 'Supplies', amount: 0, transactionDate: today(), branch, paymentMethod: 'Cash', reference: '', status: 'Posted', notes: '' };
  if (kind === 'staff') return { id: newId(), isNew: true, employeeCode: 'NC-EMP-', fullName: '', role: 'Service Crew', branch, phone: '', email: '', employmentType: 'Full-time', salary: 0, startDate: today(), status: 'Active', emergencyContact: '', notes: '' };
  if (kind === 'attendance') { const member = state.staff?.[0]; return { id: newId(), isNew: true, staffId: member?.id || '', staffName: member?.fullName || '', employeeCode: member?.employeeCode || '', branch: member?.branch || branch, attendanceDate: today(), status: 'Present', clockIn: '09:00', clockOut: '', notes: '' }; }
  const member = state.staff?.[0]; return { id: newId(), isNew: true, staffId: member?.id || '', staffName: member?.fullName || '', employeeCode: member?.employeeCode || '', branch: member?.branch || branch, leaveType: 'Annual leave', startDate: today(), endDate: today(), reason: '', status: 'Pending' };
}

function CrmDrawer({ kind, record, state, onSave, onClose }) {
  const [draft, setDraft] = useState(record);
  const update = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const branches = branchesFor(state).filter((item) => item !== 'All branches');
  const staffOptions = (state.staff || []).map((item) => ({ value: item.id, label: `${item.fullName} · ${item.employeeCode}` }));
  const definitions = {
    finance: { title: 'Finance transaction', fields: [['type', 'Type', 'select', ['Income', 'Expense']], ['description', 'Description', 'text'], ['category', 'Category', 'select', ['Food sales', 'Delivery sales', 'Catering', 'Rent', 'Payroll', 'Utilities', 'Supplies', 'Marketing', 'Maintenance', 'Other']], ['amount', 'Amount (RM)', 'number'], ['transactionDate', 'Transaction date', 'date'], ['branch', 'Branch', 'select', branches], ['paymentMethod', 'Payment method', 'select', ['Cash', 'Card', 'Online', 'Bank transfer', 'Other']], ['reference', 'Reference / receipt no.', 'text'], ['status', 'Status', 'select', ['Posted', 'Pending', 'Void']], ['notes', 'Notes', 'textarea']] },
    staff: { title: 'Staff member', fields: [['employeeCode', 'Employee ID', 'text'], ['fullName', 'Full name', 'text'], ['role', 'Role', 'select', ['Restaurant Manager', 'Chef', 'Kitchen Staff', 'Service Crew', 'Cashier', 'Delivery Rider', 'HR / Admin', 'Other']], ['branch', 'Branch', 'select', branches], ['phone', 'Phone', 'tel'], ['email', 'Email', 'email'], ['employmentType', 'Employment type', 'select', ['Full-time', 'Part-time', 'Contract']], ['salary', 'Monthly salary (RM)', 'number'], ['startDate', 'Start date', 'date'], ['status', 'Status', 'select', ['Active', 'On Leave', 'Inactive']], ['emergencyContact', 'Emergency contact', 'text'], ['notes', 'Notes', 'textarea']] },
    attendance: { title: 'Attendance record', fields: [['staffId', 'Staff member', 'select', staffOptions], ['attendanceDate', 'Date', 'date'], ['status', 'Status', 'select', ['Present', 'Absent', 'Late', 'Leave']], ['clockIn', 'Clock in', 'time'], ['clockOut', 'Clock out', 'time'], ['notes', 'Notes', 'textarea']] },
    leave: { title: 'Leave request', fields: [['staffId', 'Staff member', 'select', staffOptions], ['leaveType', 'Leave type', 'select', ['Annual leave', 'Medical leave', 'Emergency leave', 'Unpaid leave', 'Other']], ['startDate', 'Start date', 'date'], ['endDate', 'End date', 'date'], ['reason', 'Reason', 'textarea'], ['status', 'Status', 'select', ['Pending', 'Approved', 'Rejected']]] },
  };
  const definition = definitions[kind];
  const submit = (event) => { event.preventDefault(); const member = kind === 'attendance' || kind === 'leave' ? (state.staff || []).find((item) => item.id === draft.staffId) : null; onSave({ ...draft, ...(member ? { staffName: member.fullName, employeeCode: member.employeeCode, branch: member.branch } : {}), salary: kind === 'staff' ? Number(draft.salary || 0) : draft.salary }); };
  return <div className="admin-drawer-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="admin-drawer"><div className="admin-drawer-head"><div><span className="admin-eyebrow">{record.isNew ? 'Create record' : 'Edit record'}</span><h2>{definition.title}</h2></div><button className="admin-icon-button" onClick={onClose} aria-label="Close editor"><X size={18} /></button></div><form className="admin-form admin-drawer-form" onSubmit={submit}><div className="admin-drawer-fields">{definition.fields.map(([key, label, type, options]) => <label key={key}>{label}{type === 'select' ? <select value={draft[key] ?? ''} onChange={(event) => update(key, event.target.value)} required={['type', 'category', 'transactionDate', 'branch', 'status', 'fullName', 'staffId', 'attendanceDate'].includes(key)}><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={typeof option === 'string' ? option : option.value} value={typeof option === 'string' ? option : option.value}>{typeof option === 'string' ? option : option.label}</option>)}</select> : type === 'textarea' ? <textarea rows="3" value={draft[key] ?? ''} onChange={(event) => update(key, event.target.value)} /> : <input type={type} value={draft[key] ?? ''} onChange={(event) => update(key, event.target.value)} required={['description', 'amount', 'transactionDate', 'fullName', 'employeeCode', 'attendanceDate'].includes(key)} min={type === 'number' ? 0 : undefined} />}</label>)}</div><div className="admin-drawer-actions"><button type="button" className="admin-outline-button" onClick={onClose}>Cancel</button><button className="admin-primary-button" type="submit"><Save size={15} />Save record</button></div></form></aside></div>;
}
